on:
  push:
    paths:
    - 'src/laboratory/**'
    - 'src/laboratory.test/**'
  pull_request:
    paths:
    - 'src/laboratory/**'
    - 'src/laboratory.test/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'

    - run: dotnet build -c Release
      working-directory: src/laboratory

    - run: dotnet test -c Release
      working-directory: src/laboratory.test
